POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer 5f4604d5d25f023918138fce

{
        "content":"Posting Single Page appe useing Authorization",
        "important": true
}